### ISSUE TITLE
How are table names whose length would exceed Excel limits handled?

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#12]

**Comment by kindly** [comment]
Currently it truncates at the max length, but will raise an error if 2 columns end the same name.

I have thought of naming scheme that I want to implement to fix this but have not got round to implementing it yet.

It is essentially the same as flatten-tools but the path parts, but instead of being configured is dynamic and tries to let each element of the path be as long as they can be.

### Vague algorithm: 

**Keep the whole of last element in the path to the table:**
len(rest_of_table) = 31 - len(last_path_element)

**Divide the number of element of path by the rest:**
length_of_each_part_of_path_with_seperator = len(rest_of_table)/(number_of_path_elements-1)

**Take away seperator length:**
length_of_each_part_of_path = length_of_each_part_of_path_with_seperator - len(seperator)

Then truncate each path part to length_of_each_part_of_path and join together with separator.

If length_of_each_part_of_path == 0, just use last_path_element. Truncate and error if there are still issues after this.

**Comment by jpmckinney** [comment]
For OCDS `contracts_implementation_transactions_payer` and `contracts_implementation_transactions_payee` will end up causing an error. #9 is one way to avoid the error. Some built-in fix as you suggest would also be nice.

**Comment by kindly** [comment]
This is fixed with the above appreach. 
See testcases here:
https://github.com/kindly/libflatterer/blob/main/src/lib.rs#L1935


For example `contracts_implementation_transactions_payer` will now be `contrac_impleme_transac_payer`.  
Alse can use tables.csv file #9 now.
