### ISSUE TITLE
What is the effect of changing field_type and count in the fields file?

### ISSUE THREAD

**Issue by jpmckinney** [kindly/flatterer#8]
https://flatterer.opendata.coop/options.html#fields-file

As I understand, the user has no choice with respect to table_name and field_name – they need to match what the tool generates when `--fields` is not specified. `field_title` changes the CSV column heading. The row order changes the column order. What do the `field_type` and `count` columns do?

**Comment by kindly** [comment]
`count` does not effect the output in any way. `field_type` in practice does not effect the output unless you use it on a field that is not in the data.  The typeguessing will override anything specified at the moment.

They are both in the generated `fields.csv` so that is why they are in the example.

`field_type` is currently required in the input but on reflection does not need to be.

Just added an issue to have a way to name and order the tables too #9.

**Comment by kindly** [comment]
`field_type` is now optional and docs are made clearer.
